### ISSUE TITLE
Implement Combobox component

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/macaw-ui#320]
### What I'm trying to achieve

I want to have the Combobox component in the new MacawUI

### Describe a proposed solution

Combine the existing `Input` component and `Downshift` library to create the `Select` component

```[tasklist]
### Tasks
- [x] Combine the `Input` component and `Downshift` library
- [x] Add different states and variants
- [x] Refactor `Input` to `BaseInput`
- [x] Export `Combobox` from MacawUI
```

### Screenshots or mockups

![image (1)](https://user-images.githubusercontent.com/9116238/229481451-a451ed11-3b5a-44fb-a2e3-ff5afd62da5c.png)

**Comment by krzysztofzuraw** [comment]
Link for preview: https://macaw-ui-next-guq22ee8q-saleorcommerce.vercel.app/?path=/story/components-combobox--default @pfils1

**Comment by timuric** [comment]
Looks like incorrect state

![Image](https://user-images.githubusercontent.com/4006792/230043875-50b8110b-5e03-49e2-9101-a11cf52b061a.png)

**Comment by timuric** [comment]
No pointer cursor on this element 

![Image](https://user-images.githubusercontent.com/4006792/230327665-b03d9840-5c0f-4df1-8ada-fc0877c887da.png)
