### ISSUE TITLE
[Feature] Cleanup repository structure

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/macaw-ui#599]
### AC
- `canary` branch is for new MacawUI development and don't have any references to legacy code
- `main` branch is for legacy MacawUI and keep for now to be backwards compatible
- Projects that use MacawUI will alias legacy MacawUI and new MacawUI on their end

```[tasklist]
### Tasks
- [x] Remove legacy folder
- [x] Remove not needed exports in pkg.json
- [x] Test exports in https://arethetypeswrong.github.io/
- [ ] Check if there are changes that need to be ported into legacy MacawUI
- [x] Release new version from branch and check with dashboard if it is working
```
